services:
  mysql:
    image: mysql:8.0
    container_name: phishguard-mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: phishguard_dev
      MYSQL_DATABASE: phishguard
      MYSQL_USER: phishguard
      MYSQL_PASSWORD: phishguard_dev
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/migration:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - phishguard-net

  redis:
    image: redis:7-alpine
    container_name: phishguard-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - phishguard-net

volumes:
  mysql_data:
  redis_data:

networks:
  phishguard-net:
    driver: bridge
