package handler

import (
	"fmt"
	"net/http"
	"sort"
	"strconv"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jung-kurt/gofpdf"
	"github.com/phishguard/phishguard/internal/middleware"
	"github.com/phishguard/phishguard/internal/model"
)

func (h *Handler) ExportCampaignPDFReal(c *gin.Context) {
	tid := *middleware.GetContextTenantID(c)
	cid, err := strconv.ParseInt(c.Param("id"), 10, 64)
	if err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "invalid campaign id"})
		return
	}

	var campaign model.Campaign
	if err := h.DB.Where("id = ? AND tenant_id = ?", cid, tid).First(&campaign).Error; err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "campaign not found"})
		return
	}

	funnel, err := h.ResultRepo.GetFunnelStats(tid, cid)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	depts, err := h.ResultRepo.GetDepartmentStats(tid, cid)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": err.Error()})
		return
	}

	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetAutoPageBreak(true, 20)
	pdf.AddPage()

	// Title
	pdf.SetFont("Helvetica", "B", 22)
	pdf.CellFormat(0, 12, "PhishGuard - Campaign Report", "", 1, "C", false, 0, "")
	pdf.Ln(8)

	// Campaign info
	pdf.SetFont("Helvetica", "", 12)
	pdf.CellFormat(0, 7, fmt.Sprintf("Campaign: %s", campaign.Name), "", 1, "", false, 0, "")
	pdf.CellFormat(0, 7, fmt.Sprintf("Status: %s", campaign.Status), "", 1, "", false, 0, "")
	launched := "N/A"
	if campaign.LaunchedAt != nil {
		launched = campaign.LaunchedAt.Format("2006-01-02 15:04:05")
	}
	pdf.CellFormat(0, 7, fmt.Sprintf("Launched: %s", launched), "", 1, "", false, 0, "")
	pdf.Ln(4)

	// Separator
	pdf.SetDrawColor(180, 180, 180)
	pdf.Line(10, pdf.GetY(), 200, pdf.GetY())
	pdf.Ln(6)

	// Phishing Funnel section
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(0, 10, "Phishing Funnel", "", 1, "", false, 0, "")
	pdf.Ln(2)

	// Table header
	colW := []float64{60, 40, 40}
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetFillColor(230, 230, 230)
	pdf.CellFormat(colW[0], 8, "Metric", "1", 0, "C", true, 0, "")
	pdf.CellFormat(colW[1], 8, "Count", "1", 0, "C", true, 0, "")
	pdf.CellFormat(colW[2], 8, "Rate", "1", 1, "C", true, 0, "")

	pdf.SetFont("Helvetica", "", 11)
	pct := func(n int64) string {
		if funnel.Total == 0 {
			return "0.00%"
		}
		return fmt.Sprintf("%.2f%%", float64(n)/float64(funnel.Total)*100)
	}
	rows := []struct{ label string; count int64 }{
		{"Sent", funnel.Sent},
		{"Opened", funnel.Opened},
		{"Clicked", funnel.Clicked},
		{"Submitted", funnel.Submitted},
		{"Reported", funnel.Reported},
	}
	for _, r := range rows {
		pdf.CellFormat(colW[0], 7, r.label, "1", 0, "", false, 0, "")
		pdf.CellFormat(colW[1], 7, strconv.FormatInt(r.count, 10), "1", 0, "R", false, 0, "")
		pdf.CellFormat(colW[2], 7, pct(r.count), "1", 1, "R", false, 0, "")
	}
	pdf.Ln(8)

	// Department Risk Ranking section
	pdf.SetFont("Helvetica", "B", 16)
	pdf.CellFormat(0, 10, "Department Risk Ranking", "", 1, "", false, 0, "")
	pdf.Ln(2)

	// Sort by click rate descending
	sort.Slice(depts, func(i, j int) bool {
		ri, rj := float64(0), float64(0)
		if depts[i].Total > 0 {
			ri = float64(depts[i].Clicked) / float64(depts[i].Total)
		}
		if depts[j].Total > 0 {
			rj = float64(depts[j].Clicked) / float64(depts[j].Total)
		}
		return ri > rj
	})

	dColW := []float64{50, 30, 30, 40}
	pdf.SetFont("Helvetica", "B", 11)
	pdf.SetFillColor(230, 230, 230)
	pdf.CellFormat(dColW[0], 8, "Department", "1", 0, "C", true, 0, "")
	pdf.CellFormat(dColW[1], 8, "Total", "1", 0, "C", true, 0, "")
	pdf.CellFormat(dColW[2], 8, "Clicked", "1", 0, "C", true, 0, "")
	pdf.CellFormat(dColW[3], 8, "Click Rate", "1", 1, "C", true, 0, "")

	pdf.SetFont("Helvetica", "", 11)
	for _, d := range depts {
		rate := "0.00%"
		if d.Total > 0 {
			rate = fmt.Sprintf("%.2f%%", float64(d.Clicked)/float64(d.Total)*100)
		}
		dept := d.Department
		if dept == "" {
			dept = "(unknown)"
		}
		pdf.CellFormat(dColW[0], 7, dept, "1", 0, "", false, 0, "")
		pdf.CellFormat(dColW[1], 7, strconv.FormatInt(d.Total, 10), "1", 0, "R", false, 0, "")
		pdf.CellFormat(dColW[2], 7, strconv.FormatInt(d.Clicked, 10), "1", 0, "R", false, 0, "")
		pdf.CellFormat(dColW[3], 7, rate, "1", 1, "R", false, 0, "")
	}

	// Footer
	pdf.Ln(12)
	pdf.SetFont("Helvetica", "I", 9)
	pdf.SetTextColor(128, 128, 128)
	pdf.CellFormat(0, 6, fmt.Sprintf("Generated by PhishGuard | %s", time.Now().Format("2006-01-02 15:04:05")), "", 1, "C", false, 0, "")

	c.Header("Content-Type", "application/pdf")
	c.Header("Content-Disposition", "attachment; filename=campaign_report.pdf")
	if err := pdf.Output(c.Writer); err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"error": "failed to generate PDF"})
	}
}
